name: Minervini Auto Screener

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and Run
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        pip install yfinance pandas requests lxml beautifulsoup4 html5lib
        echo "=========================================="
        echo "🔍 컴퓨터가 보는 현재 폴더 파일 목록:"
        ls -la
        echo "=========================================="
        python screener.py
